name: 🔬 Deploy test version [auto]

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - "README*.md"
      - ".gitignore"
      - ".github/**"
      - ".vscode/**"
      - "Makefile"
      - "examples/**"
      - ".bumpversion.cfg"
      - "pyproject.toml"

concurrency:
  group: staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install build-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-build.txt

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Bump up package version
        id: bumpversion
        run: |
          bump2version patch --verbose
          VERSION=$(bump2version --dry-run --list src | grep new_version= | sed -r s,"^.*=",,)
          echo "[debug] new_version=$VERSION"
          echo "new_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Add and push changes
        run: |
          git add .
          git push
        env:
          GIT_TOKEN: ${{ secrets.GH_PAT }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.bumpversion.outputs.new_version }}
          release_name: Release ${{ steps.bumpversion.outputs.new_version }}
          draft: false
          prerelease: true

      - name: Build package and publish
        working-directory: src
        run: |
          python -m build
          python -m twine upload \
          --repository testpypi \
          --username '__token__' \
          --password '${{ secrets.TEST_PYPI_TOKEN }}' \
          dist/* \
          --verbose
